language: node_js
sudo: false
node_js:
  - 8
install:
  - npm i vuepress macaca-ecosystem
script:
  - npm run docs:build
  - cd ./docs
  - git init
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$REPO_TOKEN@github.com/macacajs/app-inspector.git master:gh-pages
  - cd ..
  - npm i
  - npm run lint
  - npm run build
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
